In [17]:

from ImportUtils import *

import pandas as pf
import numpy as np

from main import dicParams, dicFiles
from ImportUtils import *

In [4]:

dfGeo = get_dfGeo_from_Parquet()
dfCursos = get_dfCursos_from_Parquet()
dfExames = get_dfExames_from_Parquet()
dfSchools = get_dfSchools_from_Parquet()
dfResultados = get_dfResultados_from_Parquet()
fResultAnalise = get_dfResultAnalise_from_Parquet()

In [24]:
dfFullSchools = dfSchools.merge(dfGeo, left_on=['Distrito', 'Concelho'], right_on=['Distrito', 'Concelho'], how='left')

In [16]:
print("dfSchools:", dfSchools.shape)
print("dfGeo:", dfGeo.shape)
#print("dfFullSchools:", dfFullSchool.shape)

dfSchools: (724, 7)
dfGeo: (309, 6)
dfFullSchools: (724, 11)

In [18]:
dfAll = get_dfAll_from_Parquet()

In [19]:
dfAll

,ano,ID,Escola,Fase,Exame,ParaAprov,Interno,ParaMelhoria,ParaIngresso,ParaCFCEPE,...,DescrEscola,PubPriv,CodDGEEC,Descr,DescrDistrito,DescrConcelho,Nuts3,DescrNuts3,DescrExame,TipoExame
0,2022,1,0002,1,639,N,N,S,S,N,...,Escola Básica e Secundária de Michel Giacomett...,PUB,1511640,None,Setúbal,Sesimbra,170,Área Metropolitana de Lisboa,Português,N
1,2022,2,0002,1,639,N,N,N,S,N,...,Escola Básica e Secundária de Michel Giacomett...,PUB,1511640,None,Setúbal,Sesimbra,170,Área Metropolitana de Lisboa,Português,N
2,2022,3,0002,1,639,N,N,N,S,N,...,Escola Básica e Secundária de Michel Giacomett...,PUB,1511640,None,Setúbal,Sesimbra,170,Área Metropolitana de Lisboa,Português,N
3,2022,4,0002,1,639,N,N,N,S,N,...,Escola Básica e Secundária de Michel Giacomett...,PUB,1511640,None,Setúbal,Sesimbra,170,Área Metropolitana de Lisboa,Português,N
4,2022,5,0002,1,639,N,N,N,S,N,...,Escola Básica e Secundária de Michel Giacomett...,PUB,1511640,None,Setúbal,Sesimbra,170,Área Metropolitana de Lisboa,Português,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5901331,2020,108193,0665,1,848,N,N,N,S,N,...,"Escola Básica e Secundária Anselmo de Andrade,...",PUB,1503057,None,Setúbal,Almada,170,Área Metropolitana de Lisboa,Mandarim (iniciação),N
5901332,2020,155992,0861,1,848,N,N,N,S,N,...,"Escola Secundária Eng. Acácio Calazans Duarte,...",PUB,1010623,None,Leiria,Marinha Grande,16F,Região de Leiria,Mandarim (iniciação),N
5901333,2020,155993,0861,1,848,N,N,N,S,N,...,"Escola Secundária Eng. Acácio Calazans Duarte,...",PUB,1010623,None,Leiria,Marinha Grande,16F,Região de Leiria,Mandarim (iniciação),N
5901334,2020,155994,0861,1,848,N,N,N,S,N,...,"Escola Secundária Eng. Acácio Calazans Duarte,...",PUB,1010623,None,Leiria,Marinha Grande,16F,Região de Leiria,Mandarim (iniciação),N
5901335,2008,346966,1042,2,450,S,N,N,N,?,...,Escola Básica e Secundária de Muralhas do Minh...,PUB,1608480,None,Viana do Castelo,Valença,111,Alto Minho,Inglês (iniciação -bienal),?

In [7]:

print("dfSchools.shape: ", dfSchools.shape)
print("dfGeo.shape: ", dfGeo.shape)
dfFullSchools = dfSchools.merge(dfGeo, left_on=['Distrito', 'Concelho'], right_on=['Distrito', 'Concelho'], how='inner')
print("dfFullSchools.shape (inner join): ", dfFullSchools.shape)
# dfFullSchools = dfSchools.merge(dfGeo, left_on=['Distrito', 'Concelho'], right_on=['Distrito', 'Concelho'], how='left')
# print("dfFullSchools.shape (left join - all schools): ", dfFullSchools.shape)
# dfFullSchools = dfSchools.merge(dfGeo, left_on=['Distrito', 'Concelho'], right_on=['Distrito', 'Concelho'], how='right')
# print("dfFullSchools.shape (right join - all Geos): ", dfFullSchools.shape)

dfSchools.shape:  (724, 8)
dfGeo.shape:  (309, 6)
dfFullSchools.shape (inner join):  (724, 12)
dfFullSchools.shape (left join - all schools):  (724, 12)
dfFullSchools.shape (right join - all Geos):  (757, 12)

In [8]:

print("....")
print("dfResultados.shape: ", dfResultados.shape)
print("dfFullSchools.shape: ", dfFullSchools.shape)
dfAll1 = dfResultados.merge(dfFullSchools, left_on=['Escola'], right_on=['Escola'], how='inner')
print("dfAll1.shape inner: ", dfAll1.shape)
dfAll1 = dfResultados.merge(dfFullSchools, left_on=['Escola'], right_on=['Escola'], how='left')
print("dfAll1.shape left (resultados): ", dfAll1.shape)
dfAll1 = dfResultados.merge(dfFullSchools, left_on=['Escola'], right_on=['Escola'], how='right')
print("dfAll1.shape right (schools): ", dfAll1.shape)

....
dfResultados.shape:  (5901336, 18)
dfFullSchools.shape:  (757, 12)
dfAll1.shape inner:  (5968595, 29)
dfAll1.shape left (resultados):  (5968595, 29)
dfAll1.shape right (schools):  (5968628, 29)

In [14]:
# Select records in dfSchools that have no match on attribute Escola in dfResultados
dfSchoolsNoMatch = dfSchools[~dfSchools.Escola.isin(dfResultados.Escola)]
print("dfSchoolsNoMatch.shape: ", dfSchoolsNoMatch.shape)
# Select records in dfResultados that have no match on attribute Escola in dfSchools
dfResultadosNoMatch = dfResultados[~dfResultados.Escola.isin(dfSchools.Escola)]
print("dfResultadosNoMatch.shape: ", dfResultadosNoMatch.shape)

# Find duplicate Escola in dfSchools
dfSchoolsDup = dfSchools[dfSchools.duplicated(['Escola'], keep=False)]
print("dfSchoolsDup.shape: ", dfSchoolsDup.shape)
# Find duplicate Escola in dfResultados
print("dfSchoolsDup: ")
print( list(dfSchoolsDup["Escola"]))

# List schools whose Escola is in dfSchoolsDup, ordered by Escola
dfSchoolsDupList = dfSchools[dfSchools.Escola.isin(dfSchoolsDup.Escola)]

print("dfSchoolsDupList.shape: ", dfSchoolsDupList.shape)
print("dfSchoolsDupList: ")
print( dfSchoolsDupList.sort_values(by=['Escola']))

# For each duplication keep just the school with the most recent AnoDadosEscola, delete the others
dfSchoolsDupList = dfSchoolsDupList.sort_values(by=['Escola', 'AnoDadosEscola'], ascending=False)
dfSchoolsDupList = dfSchoolsDupList.drop_duplicates(subset=['Escola'], keep='first')
print("dfSchoolsDupList.shape: ", dfSchoolsDupList.shape)
print("dfSchoolsDupList: ")

dfSchoolsNoMatch.shape:  (0, 8)
dfResultadosNoMatch.shape:  (0, 18)
dfSchoolsDup.shape:  (20, 8)
dfSchoolsDup:
['0480', '0486', '0677', '0969', '1010', '2407', '2539', '2543', '2633', '2406', '2633', '0480', '0486', '0677', '0969', '1010', '2406', '2407', '2539', '2543']
dfSchoolsDupList.shape:  (20, 8)
dfSchoolsDupList:
     AnoDadosEscola Distrito Concelho Escola  \
129            2022       11       16   0480
709            2008       11       07   0480
135            2022       11       16   0486
710            2008       11       07   0486
214            2022       11       16   0677
711            2008       11       07   0677
403            2022       11       16   0969
713            2008       11       07   0969
433            2022       05       06   1010
714            2008       05       04   1010
717            2008       10       09   2406
656            2019       10       15   2406
549            2022       10       15   2407
718            2008       10       09   2407
720            2008       11       07   2539
570            2022       11       16   2539
571            2022       11       16   2543
721            2008       11       07   2543
594            2022       13       17   2633
687            2014       13       12   2633

                                           DescrEscola PubPriv CodDGEEC  \
129  Escola Secundária Braamcamp Freire, Pontinha, ...     PUB  1107245
709                                               None     PUB  1107999
135  Escola Secundária Pedro Alexandrino, Póvoa de ...     PUB  1107558
710                                               None     PUB  1107999
214             Escola Secundária de Caneças, Odivelas     PUB  1107812
711                                               None     PUB  1107999
403              Escola Secundária da Ramada, Odivelas     PUB  1107403
713                                               None     PUB  1107999
433  Escola Básica e Secundária Padre António de An...     PUB   506188
714                                               None     PUB   504999
717                                               None     PRI  1009999
656                                               None     PRI  1015777
549                             Colégio João de Barros     PRI  1015672
718                                               None     PRI  1009999
720                                               None     PRI  1107999
570                            Externato Flor do Campo     PRI  1107809
571                   Instituto de Ciências Educativas     PRI  1107824
721                                               None     PRI  1107999
594                                  Colégio Horizonte     PRI  1312899
687                                               None     PRI  1312999

                                             Descr
129                                           None
709  Escola Secundária Braancamp Freire - Pontinha
135                                           None
710            Escola Secundária Pedro Alexandrino
214                                           None
711                   Escola Secundária de Caneças
403                                           None
713                    Escola Secundária da Ramada
433                                           None
714      Escola EB23/S de Padre António de Andrade
717                            Colégio Cidade Roda
656                            Colégio Cidade Roda
549                                           None
718                         Colégio João de Barros
720                        Externato Flor do Campo
570                                           None
571                                           None
721               Instituto de Ciências Educativas
594                                           None
687                              Colégio Horizonte

In [ ]:

print("....")
print("dfAll1.shape: ", dfAll1.shape)
print("dfExames.shape: ", dfExames.shape)
dfAll = dfAll1.merge(dfExames, left_on=['ano', 'Exame'], right_on=['ano', 'Exame'], how='inner')
print("dfAll.shape: ", dfAll.shape)
dfAll = dfAll1.merge(dfExames, left_on=['ano', 'Exame'], right_on=['ano', 'Exame'], how='left')
print("dfAll.shape left (dfAll1): ", dfAll.shape)
dfAll = dfAll1.merge(dfExames, left_on=['ano', 'Exame'], right_on=['ano', 'Exame'], how='right')
print("dfAll.shape right (dfExames): ", dfAll.shape)